# Generated by Django 5.0.7 on 2024-07-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_items',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_items',
            field=models.ManyToManyField(related_name='menus', to='menu.menuitem'),
        ),
    ]
